"""Security report generator — produces SECURITY.md from scan results."""

import json
from datetime import datetime, timezone
from typing import Dict

from loguru import logger
from pydantic import Field


def register_report_tool(mcp, handle_exceptions):
    """Register the report generation tool with the MCP server."""

    @mcp.tool()
    @handle_exceptions
    async def generate_security_report(
        project_name: str = Field(description='Name of the project being analyzed'),
        scan_results: str = Field(
            description='JSON string with scan results from scan_with_checkov, '
            'scan_with_semgrep, scan_with_bandit, or any other scanning tool. '
            'Can be a single result object or an array of result objects.'
        ),
    ) -> Dict:
        """Generate a SECURITY.md report from scan results.

        Takes output from one or more security scans and produces a structured
        Markdown report with executive summary, STRIDE threat model, compliance
        notes, and prioritized recommendations.
        """
        try:
            results = json.loads(scan_results)
        except json.JSONDecodeError:
            return {"success": False, "error": "Invalid JSON in scan_results"}

        if isinstance(results, dict):
            results = [results]

        now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')

        all_findings = []
        scanner_summaries = []
        for r in results:
            tool = r.get('tool', 'unknown')
            findings = r.get('findings', [])
            summary = r.get('summary', {})

            critical = summary.get('critical', 0)
            high = summary.get('high', summary.get('error', 0))
            medium = summary.get('medium', summary.get('warning', 0))
            low = summary.get('low', summary.get('info', 0))

            scanner_summaries.append({
                'tool': tool, 'total': r.get('total_issues', len(findings)),
                'critical': critical, 'high': high, 'medium': medium, 'low': low,
                'format': r.get('format_type', r.get('language', 'N/A')),
            })

            for f in findings:
                f['_tool'] = tool
                f['_severity'] = (f.get('severity') or f.get('issue_severity') or 'MEDIUM').upper()
            all_findings.extend(findings)

        total_findings = len(all_findings)
        total_critical = sum(s['critical'] for s in scanner_summaries)
        total_high = sum(s['high'] for s in scanner_summaries)

        if total_critical > 0:
            risk_level = '🔴 CRITICAL'
        elif total_high > 0:
            risk_level = '🟠 HIGH'
        elif total_findings > 0:
            risk_level = '🟡 MEDIUM'
        else:
            risk_level = '🟢 LOW'

        lines = [
            '# Security Report', '',
            '> Generated by MCP Security Scanner',
            f'> Date: {now}', f'> Project: {project_name}', '',
            '## Executive Summary', '',
            f'**Risk Level:** {risk_level}',
            f'**Total Findings:** {total_findings}', '',
            '## Scan Results', '',
            '| Scanner | Format/Language | Findings | Critical | High | Medium | Low |',
            '|---------|---------------|----------|----------|------|--------|-----|',
        ]
        for s in scanner_summaries:
            lines.append(
                f"| {s['tool'].capitalize()} | {s['format']} | {s['total']} "
                f"| {s['critical']} | {s['high']} | {s['medium']} | {s['low']} |"
            )
        lines.append('')

        critical_high = [f for f in all_findings if f['_severity'] in ('CRITICAL', 'HIGH', 'ERROR')]
        medium_low = [f for f in all_findings if f['_severity'] not in ('CRITICAL', 'HIGH', 'ERROR')]

        if critical_high:
            lines.extend(['## Critical & High Severity Findings', ''])
            for i, f in enumerate(critical_high, 1):
                fid = f.get('check_id') or f.get('rule_id') or f.get('test_id') or 'N/A'
                desc = f.get('description') or f.get('message') or f.get('check_name') or 'N/A'
                line_num = f.get('line_number') or f.get('line') or (f.get('line_range', [None])[0]) or 'N/A'
                lines.append(f'### {i}. {fid}')
                lines.append(f'- **Severity:** {f["_severity"]}')
                lines.append(f'- **Scanner:** {f["_tool"]}')
                lines.append(f'- **Line:** {line_num}')
                if f.get('resource'):
                    lines.append(f'- **Resource:** {f["resource"]}')
                lines.append(f'- **Description:** {desc}')
                if f.get('guideline'):
                    lines.append(f'- **Guideline:** {f["guideline"]}')
                lines.append('')

        if medium_low:
            lines.extend([
                '## Medium & Low Severity Findings', '',
                '| # | ID | Severity | Scanner | Line | Description |',
                '|---|-----|----------|---------|------|-------------|',
            ])
            for i, f in enumerate(medium_low, 1):
                fid = f.get('check_id') or f.get('rule_id') or f.get('test_id') or 'N/A'
                desc = (f.get('description') or f.get('message') or f.get('check_name') or 'N/A')[:80]
                line_num = f.get('line_number') or f.get('line') or 'N/A'
                lines.append(f'| {i} | {fid} | {f["_severity"]} | {f["_tool"]} | {line_num} | {desc} |')
            lines.append('')

        findings_str = str(all_findings)
        lines.extend([
            '## Threat Model Inputs', '', '### STRIDE Classification', '',
            '| Threat | Applicable | Evidence |',
            '|--------|-----------|----------|',
            f'| Spoofing | {"Yes" if any(k in findings_str for k in ["auth", "credential", "password", "token"]) else "Review needed"} | Check authentication mechanisms |',
            f'| Tampering | {"Yes" if any(k in findings_str for k in ["injection", "input", "validation", "sanitiz"]) else "Review needed"} | Check input validation |',
            f'| Repudiation | {"Yes" if any(k in findings_str for k in ["log", "audit", "trail"]) else "Review needed"} | Check logging and audit trails |',
            f'| Information Disclosure | {"Yes" if any(k in findings_str for k in ["secret", "hardcoded", "password", "key", "encrypt"]) else "Review needed"} | Check data protection |',
            f'| Denial of Service | {"Yes" if any(k in findings_str for k in ["resource", "limit", "timeout"]) else "Review needed"} | Check resource limits |',
            f'| Elevation of Privilege | {"Yes" if any(k in findings_str for k in ["iam", "privilege", "admin", "wildcard", "root"]) else "Review needed"} | Check access controls |',
            '', '## Compliance & Regulatory Notes', '',
            '> Review the findings above against your applicable compliance frameworks.',
            '> Common frameworks: SOC2, PCI-DSS, HIPAA, GDPR.', '',
            '## Recommendations', '',
        ])

        if total_critical > 0:
            lines.append('1. **IMMEDIATE:** Address all CRITICAL severity findings before deployment')
        if total_high > 0:
            lines.append(f'{2 if total_critical > 0 else 1}. **HIGH PRIORITY:** Remediate HIGH severity findings in the current sprint')
        if total_findings > 0:
            lines.append('- Review and triage MEDIUM/LOW findings for backlog prioritization')
        lines.extend([
            '- Re-scan after remediation to verify fixes',
            '- Consider adding pre-commit hooks for continuous scanning', '',
            '## Tool Information', '',
            '- Scanner: [MCP Security Scanner](https://github.com/aws-samples/sample-mcp-security-scanner)',
            '- Pattern: [AWS Prescriptive Guidance](https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/deploy-real-time-coding-security-validation-by-using-an-mcp-server-with-kiro-and-other-coding-assistants.html)',
            '',
        ])

        return {
            "success": True,
            "report": '\n'.join(lines),
            "summary": {
                "risk_level": risk_level,
                "total_findings": total_findings,
                "scanners_used": [s['tool'] for s in scanner_summaries],
            },
        }
